require "securerandom"
require "fileutils"
require "json"
require "time"
require "openssl"
require_relative "canonicalization"
require_relative "hasher"
require_relative "signer"
require_relative "file_encryptor"
require_relative "workspace"

module Kapri
  # T2 - Package Generation reference implementation.
  #
  # Implements the seven-step generation workflow defined by
  # specification/14: T2.md SS3: Generate Package Files -> Encrypt Package
  # Files, if required -> Generate Packing List -> Generate Composition ->
  # Generate Package Manifest -> Canonicalize Package Manifest ->
  # Digitally Sign Package Manifest. Each public method corresponds to one
  # T2.x conformance test and is independently callable via its own
  # script, mirroring T1's PKI module.
  #
  # The KAP-KDM is deliberately not generated here: T2 SS2.3 explicitly
  # excludes it from Package Generation ("A KAP-KDM SHALL NOT be part of
  # the Knowledge Asset Package"). It is T4's concern - see
  # Kapri::SecureDelivery.
  #
  # Every KAP document this module writes to disk (Packing List,
  # Composition, Manifest) is stored as pretty-printed JSON for
  # readability - property ordering and whitespace have no semantic
  # meaning (SC0 SS3.6). Wherever a hash or signature is computed (SC0
  # SS3.8), it is computed over the RFC 8785 (JCS) canonical form of the
  # *parsed* document, not over whatever bytes happen to be on disk - see
  # document_hash and Signer.
  #
  # output_dir is a working directory. The normative Package Container is
  # written below output_dir/package; implementation state is kept below
  # output_dir/state and never becomes part of the Package.
  module PackageGeneration
    SCHEMA_VERSION     = "0.9.0".freeze
    ORGANIZATION_ID    = "urn:kap:organization:kapri-reference".freeze
    ORGANIZATION_NAME  = "KAPRI Reference Organization".freeze
    RECIPIENT_ORGANIZATION_ID   = "urn:kap:organization:kapri-reference-recipient".freeze
    RECIPIENT_ORGANIZATION_NAME = "KAPRI Reference Recipient".freeze

    PackageFilesResult = Struct.new(:output_dir, :files, :file_keys, keyword_init: true)
    PackingListResult  = Struct.new(:output_dir, :path, :packing_list, keyword_init: true)
    CompositionResult  = Struct.new(:output_dir, :path, :composition, keyword_init: true)
    ManifestResult     = Struct.new(:output_dir, :path, :manifest, keyword_init: true)
    CanonicalizationResult = Struct.new(:output_dir, :path, :canonical_bytes, keyword_init: true)
    SignatureResult    = Struct.new(:output_dir, :path, :manifest, keyword_init: true)

    def self.uuid_urn = "urn:uuid:#{SecureRandom.uuid}"

    # T2.1 - Generate Package Files
    def self.generate_package_files(output_dir:)
      package_dir = Workspace.ensure_package_dir(output_dir)
      files_dir = File.join(package_dir, "files")
      FileUtils.mkdir_p(files_dir)

      payload = <<~TEXT
        # KAPRI Example Content

        This is an example payload generated by the KAPRI T2 reference
        implementation for conformance testing. It carries no semantic
        content.
      TEXT

      relative_path = "files/example.md"
      File.write(File.join(package_dir, relative_path), payload)

      entry = {
        "file_id" => uuid_urn, "path" => relative_path, "media_type" => "text/markdown",
        "size" => payload.bytesize, "hash_algorithm" => Hasher::ALGORITHM, "hash" => Hasher.sha256(payload)
      }

      files = [entry]
      write_internal_json(output_dir, "_package_files.json", { "files" => files, "file_keys" => {} })

      PackageFilesResult.new(output_dir: output_dir, files: files, file_keys: {})
    end

    # T2.2 - Encrypt Package Files, if required
    #
    # Encrypts every Package File T2.1 generated, in place. Not applicable
    # if the Reference Package contains no encrypted Package Files (T2 SS3
    # T2.2); callers simply skip this step in that case.
    def self.encrypt_package_files(output_dir:)
      package_dir = Workspace.ensure_package_dir(output_dir)
      state = read_internal_json(output_dir, "_package_files.json")
      files = state.fetch("files")
      raise "Keine Package Files gefunden - T2.1 zuerst ausführen" if files.empty?

      file_keys = state.fetch("file_keys", {})

      encrypted_files = files.map do |entry|
        full_path = File.join(package_dir, entry.fetch("path"))
        plaintext = File.binread(full_path)

        encrypted = FileEncryptor.encrypt(plaintext)
        File.binwrite(full_path, encrypted.stored_bytes)

        key_id = uuid_urn
        # Plaintext File Keys, kept only in reference-implementation-
        # internal state - analogous to T1 keeping PKI private keys
        # unencrypted on disk (see PKI docs): fine for a reference/test PKI
        # and reference package, not for production use.
        file_keys[key_id] = Hasher.base64url(encrypted.file_key)

        entry.merge(
          "size"           => encrypted.stored_bytes.bytesize,
          "hash_algorithm" => Hasher::ALGORITHM,
          "hash"           => Hasher.sha256(encrypted.stored_bytes),
          "key_id"         => key_id
        )
      end

      write_internal_json(output_dir, "_package_files.json", { "files" => encrypted_files, "file_keys" => file_keys })

      PackageFilesResult.new(output_dir: output_dir, files: encrypted_files, file_keys: file_keys)
    end

    # T2.3 - Generate Packing List
    def self.generate_packing_list(output_dir:)
      package_dir = Workspace.ensure_package_dir(output_dir)
      state = read_internal_json(output_dir, "_package_files.json")
      files = state.fetch("files")
      raise "Keine Package Files gefunden - T2.1 zuerst ausführen" if files.empty?

      packing_list = {
        "document_type"   => "kap_packing_list",
        "schema_version"  => SCHEMA_VERSION,
        "packing_list_id" => uuid_urn,
        "files"           => files
      }

      write_document(package_dir, "packing-list.json", packing_list)

      PackingListResult.new(output_dir: output_dir, path: File.join(package_dir, "packing-list.json"), packing_list: packing_list)
    end

    # T2.4 - Generate Composition
    def self.generate_composition(output_dir:)
      package_dir = Workspace.ensure_package_dir(output_dir)
      packing_list = read_document(package_dir, "packing-list.json")
      file_ids = packing_list.fetch("files").map { |f| f.fetch("file_id") }

      item_id = uuid_urn
      composition_id = uuid_urn

      composition = {
        "document_type"  => "kap_composition",
        "schema_version" => SCHEMA_VERSION,
        "composition_id" => composition_id,
        "items" => [
          { "item_id" => item_id, "content_id" => uuid_urn, "file_ids" => file_ids }
        ]
      }

      relative_path = File.join("compositions", "#{composition_id.delete_prefix('urn:uuid:')}.json")
      write_document(package_dir, relative_path, composition)

      CompositionResult.new(output_dir: output_dir, path: File.join(package_dir, relative_path), composition: composition)
    end

    # T2.5 - Generate Package Manifest (without signature - see T2.7)
    def self.generate_manifest(output_dir:, organization_id: ORGANIZATION_ID, organization_name: ORGANIZATION_NAME)
      package_dir = Workspace.ensure_package_dir(output_dir)
      packing_list = read_document(package_dir, "packing-list.json")

      composition_paths = Dir.glob(File.join(package_dir, "compositions", "*.json")).sort
      raise "Keine Composition gefunden - T2.4 zuerst ausführen" if composition_paths.empty?

      compositions = composition_paths.map do |path|
        doc = JSON.parse(File.read(path))
        { "document_id" => doc.fetch("composition_id"), "hash_algorithm" => Hasher::ALGORITHM, "hash" => document_hash(doc) }
      end

      manifest = {
        "document_type"                 => "kap_manifest",
        "schema_version"                => SCHEMA_VERSION,
        "package_id"                    => uuid_urn,
        "knowledge_asset_id"            => uuid_urn,
        "knowledge_asset_version_id"    => uuid_urn,
        "knowledge_asset_version_label" => "1.0",
        "title"                         => "KAPRI Reference Package",
        "publication_scope"             => "complete",
        "responsible_organization"      => { "organization_id" => organization_id, "name" => organization_name },
        "published_at"                  => Time.now.utc.iso8601,
        "packing_list" => {
          "document_id"    => packing_list.fetch("packing_list_id"),
          "hash_algorithm" => Hasher::ALGORITHM,
          "hash"           => document_hash(packing_list)
        },
        "compositions" => compositions
      }

      write_internal_json(output_dir, "_manifest_unsigned.json", manifest)

      ManifestResult.new(output_dir: output_dir, path: internal_path(output_dir, "_manifest_unsigned.json"), manifest: manifest)
    end

    # T2.6 - Canonicalize Package Manifest
    def self.canonicalize_manifest(output_dir:)
      manifest = read_internal_json(output_dir, "_manifest_unsigned.json")
      canonical_bytes = Canonicalization.serialize(manifest)
      path = internal_path(output_dir, "_manifest_canonical.jcs")
      File.binwrite(path, canonical_bytes)

      CanonicalizationResult.new(output_dir: output_dir, path: path, canonical_bytes: canonical_bytes)
    end

    # T2.7 - Digitally Sign Package Manifest
    def self.sign_manifest(output_dir:, pki_dir:)
      package_dir = Workspace.ensure_package_dir(output_dir)
      manifest = read_internal_json(output_dir, "_manifest_unsigned.json")

      producer_cert, producer_key = read_certificate_and_key(pki_dir, "producer", "producer")
      intermediate_cert, = read_certificate_and_key(pki_dir, "intermediate", "intermediate-ca")
      root_cert, = read_certificate_and_key(pki_dir, "root", "root-ca")

      signed_manifest = Signer.sign_document(
        manifest, private_key: producer_key,
        certificate_chain: [producer_cert, intermediate_cert, root_cert]
      )
      write_document(package_dir, "manifest.json", signed_manifest)

      SignatureResult.new(output_dir: output_dir, path: File.join(package_dir, "manifest.json"), manifest: signed_manifest)
    end

    def self.read_certificate_and_key(pki_dir, role_dir, basename)
      cert = OpenSSL::X509::Certificate.new(File.read(File.join(pki_dir, role_dir, "#{basename}.crt")))
      key_path = File.join(pki_dir, role_dir, "#{basename}.key")
      key = File.exist?(key_path) ? OpenSSL::PKey.read(File.read(key_path)) : nil
      [cert, key]
    end
    private_class_method :read_certificate_and_key

    # SC0 SS3.8: the hash is computed over the document's RFC 8785 (JCS)
    # canonical form, independent of how it happens to be stored on disk.
    def self.document_hash(hash)
      Hasher.sha256(Canonicalization.serialize(hash))
    end
    private_class_method :document_hash

    def self.write_document(output_dir, relative_path, hash)
      full_path = File.join(output_dir, relative_path)
      FileUtils.mkdir_p(File.dirname(full_path))
      File.write(full_path, JSON.pretty_generate(hash) + "\n")
    end
    private_class_method :write_document

    def self.read_document(output_dir, relative_path)
      JSON.parse(File.read(File.join(output_dir, relative_path)))
    end
    private_class_method :read_document

    def self.internal_path(output_dir, name) = Workspace.state_path(output_dir, name)
    private_class_method :internal_path

    def self.write_internal_json(output_dir, name, hash)
      FileUtils.mkdir_p(Workspace.state_dir(output_dir))
      File.write(internal_path(output_dir, name), JSON.pretty_generate(hash))
    end
    private_class_method :write_internal_json

    def self.read_internal_json(output_dir, name)
      JSON.parse(File.read(internal_path(output_dir, name)))
    end
    private_class_method :read_internal_json
  end
end
